# [Services]
apiVersion: v1
kind: Service
metadata:
  name: cleasing-be-svc
spec:
  ports:
  - port: 8082
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: cleasing-be
    tier: backend
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleasing-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cleasing-be
  template:
    metadata:
      labels:
        app: cleasing-be
        tier: backend
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-key
      containers:
      # [APP]
      - name: cleasing-be
        image: gcr.io/prueba-moises-gcp/cleasing-be:latest
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "500Mi"
          limits:
            cpu: "200m"
            memory: "1000Mi" 
        livenessProbe:
          httpGet:
            path: /actuator/info
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 160
          periodSeconds: 60
          timeoutSeconds: 10       
        #[env-vars]
        env:
        - name: SFTP_HOST
          value: "35.184.121.73"
        - name: SFTP_USER  
          value: "moises"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: SFTP_PSWD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: pswd