/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cleasing;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


@SpringBootApplication
public class CleansingApplication {
	
	public static void main(String[] args) {
	    SpringApplication.run(CleansingApplication.class, args);
	  }
	
    public boolean someLibraryMethod() {
        return true;
    }
}
